sudo: required
language: generic
services: docker

script:
  - docker pull alexbirne/texlive2019:latest
  # Compiling the tex file
  - docker run -v $TRAVIS_BUILD_DIR/:/mnt/TexDir alexbirne/texlive2019 /bin/bash -c "cd /mnt/TexDir; make"
  - docker run -e UPLOAD_URL=$UPLOAD_URL -e UPLOAD_FILE=$UPLOAD_FILE -e UPLOAD_PASSWORD=$UPLOAD_PASSWORD -v $TRAVIS_BUILD_DIR:/mnt/UploadDir alexbirne/uploadnextcloud
notifications:
  email:
    recipients:
      - alex.birnkraut@gmail.com
    on_success: change 
    on_failure: always