name: Build Cookbook
run-name: Building Cookbook to Nextcloud
on: 
  push:
    branches:
      - master
jobs:
  BuildCookbook:
    runs-on: ubuntu-latest
    container: alexbirne/texlive2019:latest
    steps:
      - docker run -v $GITHUB_ACTION_PATH/:/mnt/TexDir alexbirne/texlive2019 /bin/bash -c "cd /mnt/TexDir; make"
  