name: Build Cookbook
run-name: Building Cookbook to Nextcloud
on: 
  push:
    branches:
      - master
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: alexbirne/texlive2019:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build latex
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: PDF Document
          path: main.pdf
  