name: Build Cookbook
run-name: Building Cookbook to Nextcloud
on: 
  push:
    branches:
      - master
jobs:
  BuildCookbook:
  runs-on: ubuntu-latest
  steps:
    - docker pull alexbirne/texlive2019:latest
    - docker run -v $GITHUB_ACTION_PATH/:/mnt/TexDir alexbirne/texlive2019 /bin/bash -c "cd /mnt/TexDir; make"
    - docker run -e UPLOAD_URL=$UPLOAD_URL -e UPLOAD_FILE=$UPLOAD_FILE -e UPLOAD_PASSWORD=$UPLOAD_PASSWORD -v $GITHUB_ACTION_PATH:/mnt/UploadDir alexbirne/uploadnextcloud
  