name: Build Cookbook
run-name: Building Cookbook to Nextcloud
on: 
  push:
    branches:
      - master
jobs:
  BuildLatex:
    runs-on: ubuntu-latest
    container:
      image: alexbirne/texlive2019:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build latex
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: PDF Document
          path: main.pdf
  Upload2Nextcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with: 
          name: PDF Document
          path: main.pdf
      #- name: File Upload
      #  run: ./upload_nextcloud.sh
  
  