name: Build Cookbook
run-name: Building Cookbook to Nextcloud
on: 
  push:
    branches:
      - master
jobs:
  BuildLatex:
    runs-on: ubuntu-latest
    container:
      image: alexbirne/texlive2022:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build latex
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: PDF Document
          path: main.pdf
  Upload2Nextcloud:
    needs: BuildLatex
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with: 
          name: PDF Document
          path: main.pdf
      - name: Print Envs
        env: 
          UPLOAD_URL:  ${{ secrets.UPLOAD_URL }}
        run: echo $UPLOAD_URL
      - name: Upload to Nextcloud
        env:
          UPLOAD_URL:  ${{ secrets.UPLOAD_URL }}
          UPLOAD_FILE: main.pdf
          UPLOAD_USER: ${{ secrets.UPLOAD_USER }}
          UPLOAD_PASSWORD: ${{ secrets.UPLOAD_PASSWORD }}
        run: curl -u $UPLOAD_USER:$UPLOAD_PASSWORD -T "$UPLOAD_FILE" "$UPLOAD_URL/remote.php/dav/files/$UPLOAD_USER/Cookbook/"
  
  